version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/eupravaM
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network
  jelovnik-service:
    build: ./jelovnik-service
    ports:
      - "8083:8083"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/eupravaM
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "81:81"
    depends_on:
      - user-service
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27018:27018"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
