version: '3.8'

services:
  user-service:
    build: ./user-service
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/euprava
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network


  sobe-service:
    build: ./sobe-service
    ports:
      - "8082:8082"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/euprava
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  dogadjaj-service:
    build: ./dogadjaj-service
    ports:
      - "8084:8084"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/euprava
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  review-service:
    build: ./review-service
    ports:
      - "8086:8086"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/euprava
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  notification-service:
    build: ./notification-service
    ports:
      - "8088:8088"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017/euprava
      - ENABLE_BOOTSTRAP=true
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - user-service
      - sobe-service
      - dogadjaj-service
      - review-service
      - notification-service
    networks:
      - app-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
